# Generated by Django 4.2 on 2025-05-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(default='produits/default.png', upload_to='produits/'),
        ),
    ]
